config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get "users/new"

  root "static_pages#home"

  get  "/help",     to: "static_pages#help"
  get  "/about",    to: "static_pages#about"
  get  "/contact",  to: "static_pages#contact"
  get  "/signup",   to: "users#new"
  get  "/login",    to: "sessions#new"
  post "/login",    to: "sessions#create"
  delete  "/logout", to: "sessions#destroy"
  post "/signup", to: "users#create"
  get "/requests", to: "requests#show"
  get "/admin/requests", to: "admin/requests#show"

  resources :reviews do
    resources :comments
  end

  resources :categories, only: [:index, :show]
  resources :books, only: [:index, :show]
  resources :requests, only: [:add, :update]
  resources :books do
    resources :reviews
  end
  resources :users do
    member do
      get :following, :followers
    end
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :book_statuses
  resources :activities

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :categories
    resources :books do
      resources :reviews
    end
    resources :reviews do
      resources :comments
    end
    resources :requests, only:[:show, :destroy, :update]
    resources :book_statuses
  end
  resources :requests, only: [:create, :destroy, :show]

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category

  validates :title,  presence: true, uniqueness: true
  validates :author,  presence: true

  after_save :downcase_fields

  validates_numericality_of :number_of_page, greater_than: 0
  has_many :reviews, dependent: :destroy
  has_many :book_statuses, dependent: :destroy

  mount_uploader :picture, PictureUploader
  validate :picture_size

  ratyrate_rateable "user_rating"

  scope :search, ->search {where("title LIKE ? or author LIKE ?",
   "%#{search.squish}%", "%#{search.squish}%")}


  def downcase_fields
    self.title.downcase
    self.author.downcase
  end

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, t("picture.validate"))
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :logged_in_user, only: [:edit, :destroy]
  before_action :load_book, only: [:show, :update, :edit, :destroy]
  before_action :load_categories, only: [:create, :new, :edit]
  before_action :check_admin, only: [:edit, :destroy]

  def show
    @reviews = Review.order("created_at DESC").where(book_id: params[:id])
      .paginate(page: params[:page], per_page: Settings.users.per_page)
    @book_status = BookStatus.find_by book_id: @book.id, user_id: current_user.id
    if @book_status.nil?
      @book_status = current_user.book_statuses.new
      @book_status.book = @book
      @book_status.save
    end
  end

  def new
    @book = Book.new
  end

  def index
    if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC")
        .paginate page: params[:page], per_page: Settings.books.per_page_book
    else
      @books = Book.order("created_at DESC")
        .paginate page: params[:page], per_page: Settings.books.per_page_book
    end
  end

  def create
    @book = Book.new book_params
    @book.category_id = params[:category_id]
    if @book.save
      flash[:success] = t "book.book_create_success"
      redirect_to admin_books_path
    else
      flash[:danger] = t "book.book_create_fail"
      render :new
    end
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t "flash.success"
      redirect_to admin_book_path(@book)
    else
      flash[:danger] = t "flash.fail"
      render :edit
    end
  end

  def edit
  end

  def destroy
    if @book.destroy
      flash[:success] = t "book.book_delete"
      redirect_to admin_books_path
    else
      flash[:danger] = t "book.fail"
      redirect_to admin_book_path(@book)
    end
  end

  private

  def load_book
    @book = Book.find_by id: params[:id]
  end

  def book_params
    params.require(:book).permit :title, :author, :publish_date,
      :number_of_page, :category_id, :picture, :description
  end

  def load_categories
    @categories = Category.all
  end

  def check_admin
    redirect_to root_url unless current_user.is_admin?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book, only: :show
  before_action :check_book, only: :show

  def show
    @reviews = Review.all.order("created_at DESC").where(book_id: params[:id])
      .paginate(page: params[:page], per_page: Settings.users.per_page)
    @book_status = BookStatus.find_by book_id: @book.id, user_id: current_user.id
    if @book_status.nil?
      @book_status = current_user.book_statuses.new
      @book_status.book = @book
      @book_status.save
    end
  end

  def index
    if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC")
      .paginate page: params[:page], per_page: Settings.books.per_page_book
    else
      @books = Book.order("created_at DESC")
      .paginate page: params[:page], per_page: Settings.books.per_page_book
    end
  end

  def create
    @book = Book.new book_params
    if @Book.save
      flash[:success] = t "book.book_create_success"
      redirect_to books_path
    else
      flash[:danger] = t "book.book_create_fail"
      render :new
    end
  end
  private

  def load_book
    @book = Book.find_by id: params[:id]
  end

  def check_book
    unless @book
      flash[:danger] = t "flash.no_object"
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit :title, :author, :publish_date, :number_of_page
      :category_id
  end
end

app/views/admin/books/_book.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t "title.stt" %></th>
      <th><%= t "book.book_index_name" %></th>
      <th><%= t "book.book_index_author" %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each_with_index do |book, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= link_to book.title, admin_book_path(book) %></td>
        <td><%= book.author %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/books/_book_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @book] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
        <span class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </span>

        <span class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control" %>
        </span>

        <span class="form-group">
          <%= f.label :author %>
          <%= f.text_field :author, class: "form-control" %>
        </span>

        <p class="form-group">
          <%= f.label :publish_date %>
          <%= f.date_select :publish_date, order: [:month, :day, :year] %>
        </p>

        <span class="form-group">
          <%= f.label :number_of_page %>
          <%= f.number_field :number_of_page, min: 1, value: 1,
            class: "form-control" %>
        </span>

        <span class="form-group">
          <%= f.label :category_id %>
          <%= f.collection_select :category_id, Category.all, :id,
            :category_name, class: "form-control" %>
        </span>

        <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </span>

        <%= f.submit t("users.submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/books/_favorite.html.erb
<%= form_for [:admin, @book_status], html: {class: "favorite_button"},
  url: {controller: :book_statuses, action: :update}, remote: true do |f| %>
  <div><%= f.hidden_field :user_id, value: current_user.id %></div>
  <div><%= f.hidden_field :book_id, value: @book.id %></div>
  <div><%= f.hidden_field :is_favorite, value: true %></div>
  <%= f.submit t("book_status.button_favorite"), class: "btn btn-primary" %>
<% end %>

app/views/admin/books/_favorite_form.html.erb
<div id="favorite_form">
<% if @book_status.is_favorite %>
  <%= render "unfavorite" %>
<% else %>
  <%= render "favorite" %>
<% end %>
</div>

app/views/admin/books/_form_search.html.erb
<div class="custom-search-input">
  <%= form_tag(admin_books_path, method: :get) do %>
    <ul>
      <li>
        <%= label_tag :search %>
        <%= text_field_tag :search, params[:search], class: "form-control",
          placeholder: t("placeholder.search")%>
      </li>
      <li>
        <%= submit_tag t("book.search"), class: "btn btn-primary" %>
      </li>
    </ul>
  <% end %>
</div>

app/views/admin/books/_read_status_form.html.erb
<%= form_for [:admin, @book_status], html: {class: "book_status_form"} do |f| %>
  <div><%= f.hidden_field :user_id, value: current_user.id %></div>
  <div><%= f.hidden_field :book_id, value: @book.id %></div>
  <%= f.select :reading_status, options_for_select({Unread: :unread, Read: :read,
    Reading: :reading}, @book_status.reading_status),class: "selectpicker" %>
  <%= f.submit t("users.submit"), class: "btn btn-success" %>
<% end %>

app/views/admin/books/_unfavorite.html.erb
<%= form_for [:admin, @book_status], html: {class: "favorite_button"},
  url: {controller: :book_statuses, action: :update}, remote: true do |f| %>
  <div><%= f.hidden_field :user_id, value: current_user.id %></div>
  <div><%= f.hidden_field :book_id, value: @book.id %></div>
  <div><%= f.hidden_field :is_favorite, value: false %></div>
  <%= f.submit t("book_status.button_unfavorite"), class: "btn btn-primary" %>
<% end %>

app/views/admin/books/edit.html.erb
<h1><%= t "book.update" %></h1>
  <%= render "book_form" %>

app/views/admin/books/index.html.erb
<h1><%= t "book.book_page_title" %></h1>
<div class="row">
  <%= render "form_search" %>
</div>
<%= link_to t("book.new"), new_admin_book_path,
  class: "btn btn-primary glyphicon glyphicon-plus" %>
<%= render "book" %>
<%= will_paginate %>

app/views/admin/books/new.html.erb
<% provide(:title, t("books.category_button")) %>
<h1> <%= t "book.new" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @book], html: {multipart: true} do |f| %>
      <%= render "shared/error_messages", object: @book %>

      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.label :author %>
      <%= f.text_field :author, class: "form-control" %>

      <%= f.label :publish_date %>
      <%= f.date_field :publish_date %>

      <%= f.label :number_of_page %>
      <%= f.number_field :number_of_page, class: "form-control" %>

      <%= f.label :category_id %>
      <%= f.collection_select :category_id, @categories, :id, :category_name,
        class: "form-control" %>

      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>

      <%= f.submit  t("book.create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/books/picture_size.js.erb
<script type="text/javascript">
  $('#book_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/admin/books/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="show_book">
      <div class="row">
        <% if @book.picture? %>
          <%= image_tag(@book.picture.url, size: Settings.users.size,
            class: "img-thumbnail") %>
        <% else %>
          <%= image_tag("defaultcover.jpg") %>
        <% end %>
      </div>
      <div class="row">
        <b><h3><%= @book.title %></h3></b>
        <b><%= t "book.book_index_author" %></b> : <%= @book.author %></br>
        <b><%= t "book.book_index_publish_date" %></b> :
          <%= @book.publish_date.to_date.strftime("%d - %B - %Y") %>
        <%= rating_for @book, "user_rating", disable_after_rate: false%>
        <br>
        <b><%= t "book.book_index_number_of_page"%></b> : <%= @book.number_of_page %>
        <div class="action_book">
          <%= link_to edit_admin_book_path(@book) do %>
            <span class="glyphicon glyphicon-pencil" %></span>
          <% end %>
          <%= link_to [:admin, @book], method: :delete,
            data: {confirm: t("flash.check")} do %>
            <span class="glyphicon glyphicon-trash text-danger"></span>
          <% end %>
        </div>
      </div>
    </br>
    </div>
    </br>
    </br>
      <%= render "favorite_form" if logged_in? %> </br>
      <%= render "read_status_form" if logged_in? %>
    </br>
  </div>
  <div class="col-md-6">
    <div class="row">
      <div class="border_description">
        <b><h1 class="description"><%= t "book.description" %></h1></b>
          <span class="blank_between"></span>
        </br><span class="text_description"><%= @book.description %></span></br>
        </br>
      </div>
      <h1 class="review"><%= t "review.review_index_name" %><h1>
    </div>
    <div class="row">
      <%= link_to t("review.add"), new_admin_book_review_path(@book),
        class: "btn btn-primary glyphicon glyphicon-plus"%>
    </div>
    </br>
    <div class="row">
      <%= render @reviews %>
    </div>

    <script>
      $('#favorite_book_panel').hide();
      $('#read_book_panel').hide();
      $('#reading_book_panel').hide();
    </script>
  </div>
</div>