config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get "users/new"

  root "static_pages#home"

  get  "/help",     to: "static_pages#help"
  get  "/about",    to: "static_pages#about"
  get  "/contact",  to: "static_pages#contact"
  get  "/signup",   to: "users#new"
  get  "/login",    to: "sessions#new"
  post "/login",    to: "sessions#create"
  delete  "/logout", to: "sessions#destroy"
  post "/signup", to: "users#create"
  get "/requests", to: "requests#show"
  get "/admin/requests", to: "admin/requests#show"

  resources :reviews do
    resources :comments
  end

  resources :categories, only: [:index, :show]
  resources :books, only: [:index, :show]
  resources :requests, only: [:add, :update]
  resources :books do
    resources :reviews
  end
  resources :users do
    member do
      get :following, :followers
    end
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :book_statuses
  resources :activities

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :categories
    resources :books do
      resources :reviews
    end
    resources :reviews do
      resources :comments
    end
    resources :requests, only:[:show, :destroy, :update]
    resources :book_statuses
  end
  resources :requests, only: [:create, :destroy, :show]

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :update]
  before_action :find_book
  before_action :find_review, only: [:update, :destroy, :edit, :show]

  def index
  end

  def new
    @review = Review.new
  end

  def show
    flash[:danger] = t "flash.no_review" unless @review
    @comments = @review.comments.most_recent.paginate page: params[:page]
    if logged_in?
      @comment = current_user.comments.build
    end
  end


  def create
    @review = Review.new review_params
    @review.book = Book.find_by id: params[:book_id]
    @review.user = current_user
    if @review.save
      flash[:success] = t "flash.review_create_success"
      redirect_to admin_book_path(@book)
    else
      flash[:danger] = t "flash.review_create_fail"
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update_attributes review_params
      flash[:success] = t "review.updated"
      redirect_to admin_book_path(@book)
    else
      flash[:danger] = t "review.no_update"
      render :edit
    end
  end

  def destroy
    if @review.destroy
      flash[:success] = t "review.success"
      redirect_to admin_book_path(@book)
    else
      flash[:danger] = t "review.fail"
    end
  end

  private

  def review_params
    params.require(:review).permit :title, :content, :book_id, :user_id
  end

  def find_book
    @book = Book.find_by id: params[:book_id]
  end

  def find_review
    @review = Review.find_by id: params[:id]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :update]
  before_action :find_book
  before_action :find_review, only: [:update, :destroy, :edit]

  def index
  end

  def new
    @review = Review.new
  end

  def show
    @review = Review.find_by id: params[:id]
      flash[:danger] = t "flash.no_review" unless @review
      @comments = @review.comments.most_recent.paginate page: params[:page]
    if logged_in?
      @comment = current_user.comments.build
    end
  end


  def create
    @review = Review.new review_params
    @review.book = Book.find_by id: params[:book_id]
    @review.user = current_user
    if @review.save
      flash[:success] = t "flash.review_create_success"
      redirect_to book_path @book
    else
      flash[:danger] = t "flash.review_create_fail"
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update_attributes review_params
      flash[:success] = t "review.updated"
      redirect_to book_path(@book)
    else
      flash[:danger] = t "review.no_update"
      render :edit
    end
  end

  def destroy
    if @review.destroy
      flash[:success] = t "review.success"
      redirect_to book_path(@book)
    else
      flash[:danger] = t "review.fail"
    end
  end

  private

  def review_params
    params.require(:review).permit :title, :content, :book_id, :user_id
  end

  def find_book
    @book = Book.find_by id: params[:book_id]
  end

  def find_review
    @review = Review.find_by id: params[:id]
  end
end

app/views/admin/reviews/_review.html.erb
<div class="review_admin">
  <div class="row">
    <span class="review">
      <h4><b><%= link_to review.title, admin_book_review_path(@book, review)%></b>
      <h4> <small><%= t "title.by"%></small>
        <%= link_to review.user.name, review.user %></h4>
      <%= review.content %></br>
      <div class="action_review">
        <% if current_user? review.user %>
          <%= review.comments.size %>
          <%= link_to t("review.comment"),
            admin_book_review_path(@book, review) %> |
          <%= link_to edit_book_review_path(review.book, review) do %>
            <span class= "glyphicon glyphicon-pencil" ></span>
          <% end %>
        <% end %>
        <%= link_to book_review_path(review.book, review),
          method: :delete, data: {confirm: t("flash.check")} do %>
            <span class="glyphicon glyphicon-trash text-danger"></span>
        <% end %>
        <%= time_ago_in_words review.created_at %> ago
      </div>
    </span>
  </div>
</div>

app/views/admin/reviews/_review_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @book, @book.reviews.build] do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: t("placeholder.title"),
        class: "form-control" %>
      <%= f.text_area :content, placeholder: t("placeholder.review"),
        class: "form-control" %>
      <%= f.submit t("users.submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/reviews/edit.html.erb
<h1><%= t "review.update" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @book, @review] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>

        <%= f.label :content %>
        <%= f.text_field :content, class: "form-control" %>

        <%= f.submit t("users.submit"), class: "btn btn-success"  %>
    <% end %>
  </div>
</div>

app/views/admin/reviews/new.html.erb
<h1><%= t "review.add" %></h1>
<%= render "review_form" %>

app/views/admin/reviews/show.html.erb
<h1><%= t "review.review_page_title" %></h1>
<div class="container">
  <div class="container-fluid">
    <b><%= @review.title %></b></br>
    <%= @review.user.name %> </br>
    <%= @review.book.title %> </br>
    <%= @review.created_at.to_s %> </br>
    <%= @review.content %>
  </div>
  <% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="comment_form">
          <%= render "comments/comment_form" %>
        </section>
      </aside>
    </div>
  <% end %>
  <div class="col-md-8">
      <% if @review.comments.any? %>
        <div id = "comment-count">
          <%= render "comments/comment_header" %>
        </div>
          <ol class="comments">
            <%= render @comments %>
          </ol>
        <%= will_paginate @comments %>
      <% end %>
  </div>
</div>