config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get "users/new"

  root "static_pages#home"

  get  "/help",     to: "static_pages#help"
  get  "/about",    to: "static_pages#about"
  get  "/contact",  to: "static_pages#contact"
  get  "/signup",   to: "users#new"
  get  "/login",    to: "sessions#new"
  post "/login",    to: "sessions#create"
  delete  "/logout", to: "sessions#destroy"
  post "/signup", to: "users#create"
  get "/requests", to: "requests#show"
  get "/admin/requests", to: "admin/requests#show"

  resources :reviews do
    resources :comments
  end

  resources :categories, only: [:index, :show]
  resources :books, only: [:index, :show]
  resources :requests, only: [:add, :update]
  resources :books do
    resources :reviews
  end
  resources :users do
    member do
      get :following, :followers
    end
    resources :likes, only: [:index, :create, :destroy]
  end
  resources :user_relationships, only: [:create, :destroy]
  resources :book_statuses
  resources :activities

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :categories
    resources :books do
      resources :reviews
    end
    resources :reviews do
      resources :comments
    end
    resources :requests, only:[:show, :destroy, :update]
    resources :book_statuses
  end
  resources :requests, only: [:create, :destroy, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books, dependent: :destroy

  validates :category_name, presence: true, uniqueness: true
  after_save :downcase_fields

  scope :search, ->search {where("category_name LIKE ?",
    "%#{search.squish}%")}

  def downcase_fields
    self.category_name.downcase
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :is_admin, only: [:edit, :destroy]
  before_action :load_category, except: :index
  before_action :check_category, only: :show

  def show
    @books = @category.books
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "categories.create"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "categories.fail_create"
      render :new
    end
  end

  def index
    if params[:search]
      @categories = Category.search(params[:search]).order("created_at DESC")
        .paginate page: params[:page], per_page: Settings.users.per_page
    else
      @categories = Category.order(created_at: :DESC).paginate page: params[:page],
      per_page: Settings.users.per_page
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "categories.update"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "categories.fail_create"
      render :edit
    end
  end

  def edit
  end

  def destroy
    unless @category.books.any?
      if @category.destroy
        flash[:success] = t "flash.category_delete"
      else
        flash[:danger] = t "flash.fail_delete"
      end
    else
        flash[:danger] = t "flash.book_exsit"
    end
    redirect_to :back
  end

  private
  def category_params
    params.require(:category).permit :category_name, :descriptions
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end

  def check_category
    unless @category
      flash[:danger] = t "flash.no_object"
      redirect_to admin_categories_path
    end
  end

  def is_admin
    redirect_to login_path unless current_user.is_admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    if params[:search]
      @categories = Category.search(params[:search]).order("updated_at DESC")
      .paginate page: params[:page], per_page: Settings.users.per_page
    else
      @categories = Category.order("updated_at DESC").paginate page: params[:page],
      per_page: Settings.users.per_page
    end
    @books = Book.all
  end
  def show
    @category = Category.all.find_by id: params[:id]
    @books = @category.books
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t "title.stt" %></th>
      <th><%= t "categories.name" %></th>
      <th><%= t "categories.number" %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each_with_index do |category, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td class="books_in_category">
          <%= link_to category.category_name, category_path(category) %></td>
        <td><%= category.books.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/_form_search.html.erb
<div class="custom-search-input">
  <%= form_tag(categories_path, method: :get) do %>
    <ul>
      <li>
        <%= label_tag :search %>
        <%= text_field_tag :search, params[:search], class: "form-control",
          placeholder: t("placeholder.search_category")%>
      </li>
      <li>
        <%= submit_tag t("book.search"), class: "btn btn-primary" %>
      </li>
    </ul>
  <% end %>
</div>

app/views/categories/index.html.erb
<h1><%= t "title.all_categories" %></h1>
<div class="row">
  <%= render "form_search" %>
</div>
<%= render "category" %>
<%= will_paginate %>

app/views/categories/new.html.erb
<% provide(:title, t("categories.category_button")) %>
<h1> <%= t "category.new" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @category do |f| %>
      <%= render "shared/error_messages", object: @category %>

      <%= f.label :category_name %>
      <%= f.text_field :category_name, class: "form-control" %>

      <%= f.label :descriptions %>
      <%= f.text_field :descriptions, class: "form-control" %>

      <%= f.submit  t("categories.create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<h1><%= t "categories.book" %><%= @category.category_name %></h1>
<div class="row">
  <% unless @books.blank?%>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= t "title.stt" %></th>
          <th><%= t "book.book_index_name" %></th>
          <th><%= t "book.book_index_author" %></th>
          <th><%= t "book.book_index_publish_date" %></th>
          <th><%= t "book.book_index_number_of_page" %></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each_with_index do |book, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.author %></td>
            <td><%= book.publish_date.to_date %></td>
            <td><%= book.number_of_page %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h3 class="none_activity"><%= t "categories.no_book" %></h3>
  <% end %>
</div>